### ISSUE TITLE
Unable to compile / upload

### ISSUE THREAD

**Issue by F14V** [milkv-duo/duo-arduino#13] opened 2024-06-17 10:41 UTC
I am trying to compile an empty sketch but it doesn't work, the output log is completely full of errors.
I don't know if it only happens to some people, I would hope the environment was already tested before releasing.

I've been waiting for a fix before opening an issue, but I see no fix made.

The main errors/warnings have to do with redefinitions, I had to remove the Werror flag from platform.txt to get the compilation working.
Now when I try to upload, the python Serial package can't be found, I had to install it manually, but now I get "module 'serial' has no attribute 'Serial'".

The Arduino framework is supposed to be easy to work with by nature, I know it's still early in the development and maybe a lot of work happens behind the scenes, but the marketing of Arduino support was there from the beginning. Also, the latest sdk release doesn't have Arduino precompiled...

**Comment by shiptux** [comment] 2024-06-17 12:42
Hi F14V
> I am trying to compile an empty sketch but it doesn't work, the output log is completely full of errors.
> I don't know if it only happens to some people, I would hope the environment was already tested before releasing.

> I've been waiting for a fix before opening an issue, but I see no fix made.

Could you please share your error logs here? In my case, the IDE will print two warning, but no errors.
```bash
/var/home/shiptux/.arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: /var/home/shiptux/.arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/rv64imfd_zicsr/lp64d/libc_nano.a(libc_a-signalr.o): in function `_getpid_r':
(.text._getpid_r+0x0): warning: _getpid is not implemented and will always fail
/var/home/shiptux/.arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/bin/ld: /var/home/shiptux/.arduino15/packages/sophgo/tools/xpack-riscv-none-elf-gcc/13.2.0-2/bin/../lib/gcc/riscv-none-elf/13.2.0/../../../../riscv-none-elf/lib/rv64imfd_zicsr/lp64d/libc_nano.a(libc_a-signalr.o): in function `.L0 ':
(.text._kill_r+0x20): warning: _kill is not implemented and will always fail
```

**Comment by F14V** [comment] 2024-06-17 12:50
Sure, here is the whole output with a fresh reinstallation of the board package. (so without Werror removed).
[milk-v_arduino_build.log](https://github.com/user-attachments/files/15871103/milk-v_arduino_build.log)

**Comment by shiptux** [comment] 2024-06-17 13:48
> Sure, here is the whole output with a fresh reinstallation of the board package. (so without Werror removed). [milk-v_arduino_build.log](https://github.com/user-attachments/files/15871103/milk-v_arduino_build.log)

I am sure I never saw this before. Would please show your Arduino IDE version? Which board are you current use?
I guess the problem was caused by compiler.
For the windows user who installed from the JSON file, should use the default compiler:
```bash
              "host": "x86_64-mingw32",
              "archiveFileName": "xpack-riscv-none-elf-gcc-13.2.0-2-win32-x64.zip",
              "url": "https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases/download/v13.2.0-2/xpack-riscv-none-elf-gcc-13.2.0-2-win32-x64.zip",
```
I am not sure what compiler you current use.

**Comment by F14V** [comment] 2024-06-17 14:07
I am using the latest version, 2.3.2. The compiler is the one that was installed automatically, I can see the one you mentioned in the staging folder, xpack-riscv-none-elf-gcc-13.2.0-2-win32-x64.zip.
The board is the Duo, but I also tried with Duo-256M.

I also tried installing a fresh instance of Arduino IDE in Windows Sandbox, but I got the same errors.

**Comment by shiptux** [comment] 2024-06-17 14:14
> I am using the latest version, 2.3.2. The compiler is the one that was installed automatically, I can see the one you mentioned in the staging folder, xpack-riscv-none-elf-gcc-13.2.0-2-win32-x64.zip. The board is the Duo, but I also tried with Duo-256M.
> 
> I also tried installing a fresh instance of Arduino IDE in Windows Sandbox, but I got the same errors.

![image](https://github.com/milkv-duo/duo-arduino/assets/22735550/9c2cce5d-82b8-49ba-8328-0b9c345c2a24)

Tested on Windows 11 Pro.

**Comment by F14V** [comment] 2024-06-17 14:30
I tried again in Sandbox, I think I got the error wrong last time, I just saw the red output and thought it failed. Now I get the same output as you do. I will try to reinstall the IDE I guess.
Do you think it could be an incompatibility because of other platforms? (I have ESP8266, ESP32, STM and Teensy)

**Comment by shiptux** [comment] 2024-06-18 02:46
> I tried again in Sandbox, I think I got the error wrong last time, I just saw the red output and thought it failed. Now I get the same output as you do. I will try to reinstall the IDE I guess. Do you think it could be an incompatibility because of other platforms? (I have ESP8266, ESP32, STM and Teensy)

> Do you think it could be an incompatibility because of other platforms? (I have ESP8266, ESP32, STM and Teensy)

I think that may be the only reason -- Arduino IDE used the wrong compiler here, instead of Duo's compiler.

**Comment by F14V** [comment] 2024-06-18 07:21
I think it took the right compiler actually, but I did see a difference just now between our setups: I had "Compiler warnings" set to "all". Now when I set it to "Default" or "None" it seems to compile.

But I still have the upload error, I attached the output.
[milk-v_arduino_upload.log](https://github.com/user-attachments/files/15881908/milk-v_arduino_upload.log)

EDIT: nevermind, I had installed "serial" instead of "pyserial". Also, regarding this, shouldn't it have its own python virtual environment?

It finally works now! Thank you for your help!

**Comment by shiptux** [comment] 2024-06-18 08:43
> I think it took the right compiler actually, but I did see a difference just now between our setups: I had "Compiler warnings" set to "all". Now when I set it to "Default" or "None" it seems to compile.
> 
> But I still have the upload error, I attached the output. [milk-v_arduino_upload.log](https://github.com/user-attachments/files/15881908/milk-v_arduino_upload.log)
> 
> EDIT: nevermind, I had installed "serial" instead of "pyserial". Also, regarding this, shouldn't it have its own python virtual environment?
> 
> It finally works now! Thank you for your help!

Currently there is  just a description in the docs for python's serial library: "You may need to install pyserial in order to upload, and then let’s just click the Upload button to test." Making a python virtual environment sounds a better solution here, thank you for your advice.

**Comment by shiptux** [comment] 2024-06-18 09:07
> I think it took the right compiler actually, but I did see a difference just now between our setups: I had "Compiler warnings" set to "all". Now when I set it to "Default" or "None" it seems to compile.

Is there any benefit to set "Compiler warnings" to "all"?

**Comment by F14V** [comment] 2024-06-18 11:09
I somehow missed that step in the docs.

I can't remember when or why exactly I set it to all, probably used to enabling all warnings from work.

**Comment by shiptux** [comment] 2024-07-15 09:29
> I somehow missed that step in the docs.
> 
> I can't remember when or why exactly I set it to all, probably used to enabling all warnings from work.

Is it ok to close this issue?

**Comment by F14V** [comment] 2024-07-15 10:33
Yes, thanks for the help. I do however hope that the redeclaration warnings will be fixed eventually.

**Closed as completed** 2024-07-15 10:32 UTC
